# Generated by Django 4.0.3 on 2022-03-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articletag_alter_article_options_tag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletag',
            old_name='articles',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='articletag',
            old_name='tags',
            new_name='tag',
        ),
    ]
