# Generated by Django 4.0.3 on 2022-03-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_rename_article_tags_tag_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletag',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Раздел'),
        ),
    ]
