# Generated by Django 4.0.3 on 2022-03-12 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_articletag_is_main_alter_tag_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletag',
            options={'verbose_name': 'Тематики статьи', 'verbose_name_plural': 'Тематики статьи'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.RemoveField(
            model_name='articletag',
            name='is_main',
        ),
        migrations.AddField(
            model_name='articletag',
            name='scope',
            field=models.BooleanField(default=False, verbose_name='основной'),
        ),
        migrations.AlterField(
            model_name='articletag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.tag', verbose_name='Раздел'),
        ),
    ]
