# Generated by Django 4.0.3 on 2022-03-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_articletag_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleTag',
            new_name='Scope',
        ),
        migrations.RenameField(
            model_name='scope',
            old_name='scope',
            new_name='is_main',
        ),
    ]
